server:
    port: 8380
spring:
    application:
        name: hometask
    docker:
        compose:
            enabled: true
            file: docker-compose.yaml
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: "jdbc:h2:file:~/spring-boot-h2-db"
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
    data:
        redis:
            database: 1
            host: localhost
            port: 6379
            username: test
            password: mypass
            repositories:
                enabled: false